language: python

python:
    - "2.7"
    - "3.5"
    - "3.6"

install:
    - pip install -r requirements.txt coverage python-coveralls
    - python setup.py --quiet install

script:
    - python setup.py test

after_success:
    - coverage run --source fredapi.fred fredapi/tests/test_fred.py
    - coveralls
